### PR TITLE
Layers jsons: fix #94

### LINKED ISSUE #94: Convert list of layers for both templates into Json files
Place files in same folder as the SVG items. (src/layers/male and src/layers/female respectively)

This variable of the male template should be a json file that is loaded on demand:

https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L60

This is the female template:

https://github.com/ubik23/charactercreator/blob/master/src/js/globals.js#L222

### PR DESCRIPTION
**Pull request by millette**
First, forget merging the `json-yikes` branch. It was me going down a dead-end. We can discuss how asynchronous code (fetch() and other promises) "contaminate" every function that call them,generally forcing them to be async too, up the call chain.

Here, I worked around that simply by fetch(ing) the male/female json layers when the page (js) is loaded.

Next, I also fixed a bunch of warnings I was seeing regarding `layers.indexOf` not being a function. I think at one point you had a red line around the selected/highlighted male/female - I saw a glimpe of it but now it's gone...

I didn't merge directly, because of these details. Let's talk in a few hours.

### CODE REVIEW

**Comment by ubik23** [comment]
Looks great! Strange that the outline has disappeared but we already have an issue to deal with that. Merging now.

**Comment by millette** [comment]
Oh, je pensais pas que t'allais merger - je pensais en jaser avant. M'enfin. Là je mange!

**Comment by millette** [comment]
The outline is also gone from https://charactercreator.org/

As I said, while coding, I saw a glimpse of it. Actually, hovered, saw the outline, I clicked and the silouhette moved a fraction of a second faster than the outline - it was a bit weird. That code is funky!

**Comment by millette** [comment]
For comparison: https://github.com/ubik23/charactercreator/compare/json-yikes (DO-NOT-MERGE-THAT, YIKES!)

**Pull request merged**
